apiVersion: v2
name: nfs
description: Helm chart for installing a NFS server to support ReadWriteMany volumes.

type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: nfs-subdir-external-provisioner
    version: 4.0.18
    repository: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
