replicaCount: 1

nfs:
  server: nfs-server.nfs.svc.cluster.local
  path: /nfsshare

storageClass:
  name: nfs-client
  defaultClass: true
  reclaimPolicy: Delete
  accessModes: ["ReadWriteMany"]
  volumeBindingMode: Immediate
