apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: read-repo-readme
  labels:
    {{- include "basic.labels" . | nindent 4}}
spec:
  description: Clones a git repo, then echoes the README file to the stout.
  params:
    - name: repo-url
      type: string
      description: The git repo URL to clone from.
  workspaces:
    - name: shared-data
      description: |
        Workspace containing the cloned repo files, so they can be read by the next task.
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
      workspaces:
        - name: source
          workspace: shared-data
    - name: read-readme
      runAfter:
        - clone
      taskRef:
        name: read-file
      params:
        - name: path
          value: README.md
      workspaces:
        - name: source
          workspace: shared-data
