apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
  labels:
    {{- include "basic.labels" . | nindent 4 }}
spec:
  params:
    - name: url
      type: string
      description: The URL of the Git repository to clone
  steps:
    - name: clone
      image: alpine/git
      script: |
        #!/bin/sh
        set -e
        git clone $(params.url) $(workspaces.source.path)
  workspaces:
    - name: source
      description: The workspace where the repository will be cloned to.
