apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  labels:
    {{- include "nfs.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "nfs.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 2049
      targetPort: 2049
    - protocol: TCP
      port: 20048
      targetPort: 20048
    - protocol: TCP
      port: 111
      targetPort: 111
    - protocol: UDP
      port: 2049
      targetPort: 2049
    - protocol: UDP
      port: 20048
      targetPort: 20048
    - protocol: UDP
      port: 111
      targetPort: 111