apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  labels:
    {{- include "nfs.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "nfs.selectorLabels" . | nindent 4 }}
  ports:
    - name: tcp-2049
      protocol: TCP
      port: 2049
      targetPort: 2049
    - name: tcp-20048
      protocol: TCP
      port: 20048
      targetPort: 20048
    - name: tcp-111
      protocol: TCP
      port: 111
      targetPort: 111
    - name: udp-2049
      protocol: UDP
      port: 2049
      targetPort: 2049
    - name: udp-20048
      protocol: UDP
      port: 20048
      targetPort: 20048
    - name: udp-111
      protocol: UDP
      port: 111
      targetPort: 111